from typing import Dict, List


def get_geonames_codes() -> Dict[str, List[str]]:
    return {
        "mountain": ["T.MT", "T.MTS"],
        "beach": ["T.BCH", "T.BCHS"],
        "plain": ["T.PLN"],
        "lake": ["H.LK", "H.LKS"],
        "desert": ["T.DSRT"],
        "river": ["H.STM"],
        "forest": ["V.FRST", "V.TREE"],
        "park": ["L.PRK"],
    }


def get_slipo_codes() -> Dict[str, str]:
    sports = [
        "ARCHERY",
        "BASEBALL",
        "BASKETBALL",
        "BOWLING",
        "CANOE",
        "CLIMBING",
        "CRICKET",
        "DIVING",
        "FOOTBALL",
        "GOLF",
        "GYM",
        "HANDBALL",
        "HOCKEY",
        "HORSE",
        # "ICESKATING",
        # "LEISURECENTER",
        "MARINA",
        # "MOTORRACING",
        "PLAYGROUND",
        "RUGBY",
        "SHOOTING",
        "SKATING",
        # "SKIINGDOWNHILL",
        "SNOOKER",
        "SOCCER",
        "STADIUM",
        "SURFING",
        "SWIMMING",
        "TENNIS",
        "VOLLEYBALL",
        # "WATERSKI",
    ]
    tourism = [
        # "ARCHAELOGICAL",
        "ART",
        "ATTRACTION",
        "BATTLEFIELD",
        "BEACH",
        "BUNKER",
        "CASINO",
        "CASTLE",
        "CAVE",
        "CINEMA",
        "CLOCK",
        # "EVENTVENUE",
        "FOUNTAIN",
        "GATE",
        "GLACIER",
        "INFORMATION",
        "LIGHTHOUSE",
        "MEMORIAL",
        "MONUMENT",
        "MUSEUM",
        "NIGHTCLUB",
        "PEAK",
        "PEDESTRIAN",
        "RUINS",
        "SHELTER",
        "THEATRE",
        # "THEMEPARK",
        "TOWER",
        # "TOWERCOMMUNICATION",
        "VOLCANO",
        # "WATERMILL",
        # "WATERTOWER",
        # "WINDMILL",
        "WRECK",
        "ZOO",
    ]
    return {x.lower(): x for x in sports + tourism}
